# railway.toml — Docker deploy with healthcheck and env wiring
[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
start = "bash /app/start.sh"

[service.env]
APP_ENV = "production"
API_V1_STR = "/api/v1"
STORAGE_DIR = "/home/appuser/storage"
# DATABASE_URL is injected automatically when you attach the Postgres plugin
# SECRET_KEY should be set in Railway → Variables

# If you also manage volumes via TOML, keep the path consistent with STORAGE_DIR:
[[service.mounts]]
path = "/home/appuser/storage"
