"""Stage F Integration Test - CRUD + Search (cookie-based auth)"""
import sys, json, http.cookiejar, urllib.request
from datetime import datetime

BASE = "http://localhost:8000/api/v1"
jar  = http.cookiejar.CookieJar()
opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))

def post(path, body):
    data = json.dumps(body).encode()
    rq = urllib.request.Request(f"{BASE}{path}", data=data,
                                headers={"Content-Type": "application/json"}, method="POST")
    rs = opener.open(rq, timeout=15)
    return json.loads(rs.read())

OK="✅"; ERR="❌"; p=ok=fail=0

def chk(label, cond, got=None, exp=None):
    global ok, fail
    if cond:
        ok += 1; print(f"  {OK} {label}")
    else:
        fail += 1
        print(f"  {ERR} {label}  got={got!r}  want={exp!r}")

# ── 1. LOGIN ────────────────────────────────────────────────────────────────
print("\n" + "="*60)
print("STEP 1 · LOGIN")
print("="*60)
try:
    rs = post("/auth/login", {"ua_username": "vihara_admin", "ua_password": "Vihara@Admin2024"})
    cookies = {c.name for c in jar}
    chk("Login 200 OK",            True)
    chk("access_token cookie set", "access_token" in cookies, cookies)
    u = rs.get("user", {})
    chk("User returned",           bool(u.get("ua_username")))
    print(f"  → user={u.get('ua_username')}  roles={[r.get('ro_name') for r in u.get('roles',[])]}")
except Exception as e:
    print(f"  {ERR} Login failed: {e}"); import traceback; traceback.print_exc(); sys.exit(1)

# ── 2. CREATE ───────────────────────────────────────────────────────────────
print("\n" + "="*60)
print("STEP 2 · CREATE  (SAVE_STAGE_ONE) — all Stage F fields")
print("="*60)
ts     = datetime.now().strftime("%H%M%S")
# 10-digit unique mobile: 07 + mmHHMMSS
mobile = f"07{datetime.now().strftime('%m%H%M%S')}"
vh_id = created_trn = None
try:
    rs = post("/vihara-data/manage", {"action": "SAVE_STAGE_ONE", "payload": {"data": {
        "vh_vname": f"Stage-F Test {ts}",   # vh_trn auto-generated by server
        "vh_addrs": "1 Test Lane, Colombo", "vh_mobile": mobile, "vh_typ": "MAIN",
        "vh_bypass_no_detail": False,
        "vh_bypass_no_chief":  True,
        "vh_bypass_ltr_cert":  False,
        "vh_period_era":   "BUDDHIST_ERA",
        "vh_period_year":  "2567",
        "vh_period_month": "02",
        "vh_period_day":   "23",
        "vh_period_notes": "Founded 2567 BE – integration test",
        "viharadhipathi_date":     "2024-12-15",
        "vh_viharadhipathi_name":  "Ven. Test Thero",
        "vh_viharadhipathi_regn":  "BUD/001",
    }}})
    chk("status=success", rs.get("status") == "success", rs.get("status"), "success")
    if rs.get("status") != "success":
        print(f"       ↳ {rs.get('message')}  |  {rs.get('data')}")
    d = rs.get("data", {}); vh_id = d.get("vh_id"); created_trn = d.get("vh_trn")
    chk("vh_id returned",                bool(vh_id),                                vh_id, "int")
    chk("vh_bypass_no_detail = False",   d.get("vh_bypass_no_detail") is False,      d.get("vh_bypass_no_detail"), False)
    chk("vh_bypass_no_chief  = True",    d.get("vh_bypass_no_chief")  is True,       d.get("vh_bypass_no_chief"),  True)
    chk("vh_bypass_ltr_cert  = False",   d.get("vh_bypass_ltr_cert")  is False,      d.get("vh_bypass_ltr_cert"),  False)
    chk("vh_period_era = BUDDHIST_ERA",  d.get("vh_period_era")  == "BUDDHIST_ERA",  d.get("vh_period_era"),  "BUDDHIST_ERA")
    chk("vh_period_year = 2567",         d.get("vh_period_year") == "2567",          d.get("vh_period_year"), "2567")
    chk("vh_period_month = 02",          d.get("vh_period_month") == "02",           d.get("vh_period_month"), "02")
    chk("vh_period_day = 23",            d.get("vh_period_day")   == "23",           d.get("vh_period_day"),  "23")
    chk("vh_period_notes saved",         bool(d.get("vh_period_notes")))
    chk("viharadhipathi_date = 2024-12-15", str(d.get("viharadhipathi_date","")).startswith("2024-12-15"),
        d.get("viharadhipathi_date"), "2024-12-15")
    chk("workflow = S1_PENDING",         d.get("vh_workflow_status") == "S1_PENDING",
        d.get("vh_workflow_status"), "S1_PENDING")
    print(f"  → vh_id={vh_id}  trn={created_trn}")
except Exception as e:
    print(f"  {ERR} {e}"); import traceback; traceback.print_exc()

# ── 3. READ_ONE (persistence check) ─────────────────────────────────────────
print("\n" + "="*60)
print("STEP 3 · READ_ONE — DB persistence field-by-field")
print("="*60)
if vh_id:
    try:
        d = post("/vihara-data/manage", {"action":"READ_ONE","payload":{"vh_id":vh_id}}).get("data",{})
        chk("vh_bypass_no_detail = False",   d.get("vh_bypass_no_detail") is False)
        chk("vh_bypass_no_chief  = True",    d.get("vh_bypass_no_chief")  is True)
        chk("vh_bypass_ltr_cert  = False",   d.get("vh_bypass_ltr_cert")  is False)
        chk("vh_period_era = BUDDHIST_ERA",  d.get("vh_period_era")  == "BUDDHIST_ERA")
        chk("vh_period_year = 2567",         d.get("vh_period_year") == "2567")
        chk("vh_period_month = 02",          d.get("vh_period_month") == "02")
        chk("vh_period_day = 23",            d.get("vh_period_day")   == "23")
        chk("vh_period_notes persisted",     bool(d.get("vh_period_notes")))
        chk("viharadhipathi_date persisted", str(d.get("viharadhipathi_date","")).startswith("2024-12-15"))
        chk("vh_vname correct",              "Stage-F Test" in str(d.get("vh_vname","")))
    except Exception as e:
        print(f"  {ERR} {e}"); import traceback; traceback.print_exc()
else:
    print("  ⚠ Skipped — CREATE failed")

# ── 4. UPDATE_STAGE_ONE ──────────────────────────────────────────────────────
print("\n" + "="*60)
print("STEP 4 · UPDATE_STAGE_ONE — flip all toggles + change period/date")
print("="*60)
if vh_id:
    try:
        rs = post("/vihara-data/manage", {"action":"UPDATE_STAGE_ONE","payload":{"vh_id": vh_id, "data":{
            "vh_bypass_no_detail": True,
            "vh_bypass_no_chief":  False,
            "vh_bypass_ltr_cert":  True,
            "vh_period_era":   "AD",
            "vh_period_year":  "1890",
            "vh_period_month": "06",
            "vh_period_day":   "15",
            "vh_period_notes": "Amended during integration test",
            "viharadhipathi_date": "2025-06-01",
            "vh_vname": f"Stage-F UPDATED {ts}",
        }}})
        chk("status=success",                rs.get("status") == "success", rs.get("status"), "success")
        d = rs.get("data", {})
        chk("vh_bypass_no_detail = True",    d.get("vh_bypass_no_detail") is True)
        chk("vh_bypass_no_chief  = False",   d.get("vh_bypass_no_chief")  is False)
        chk("vh_bypass_ltr_cert  = True",    d.get("vh_bypass_ltr_cert")  is True)
        chk("vh_period_era = AD",            d.get("vh_period_era")  == "AD",   d.get("vh_period_era"),  "AD")
        chk("vh_period_year = 1890",         d.get("vh_period_year") == "1890", d.get("vh_period_year"), "1890")
        chk("viharadhipathi_date = 2025-06-01", str(d.get("viharadhipathi_date","")).startswith("2025-06-01"),
            d.get("viharadhipathi_date"), "2025-06-01")
        chk("vh_vname updated",              "Stage-F UPDATED" in str(d.get("vh_vname","")))
    except Exception as e:
        print(f"  {ERR} {e}"); import traceback; traceback.print_exc()

# ── 5. READ_ONE post-update (consistency) ───────────────────────────────────
print("\n" + "="*60)
print("STEP 5 · READ_ONE after UPDATE — cross-layer consistency")
print("="*60)
if vh_id:
    try:
        d = post("/vihara-data/manage", {"action":"READ_ONE","payload":{"vh_id":vh_id}}).get("data",{})
        chk("vh_bypass_no_detail = True",    d.get("vh_bypass_no_detail") is True)
        chk("vh_bypass_no_chief  = False",   d.get("vh_bypass_no_chief")  is False)
        chk("vh_bypass_ltr_cert  = True",    d.get("vh_bypass_ltr_cert")  is True)
        chk("vh_period_era = AD",            d.get("vh_period_era")  == "AD")
        chk("vh_period_year = 1890",         d.get("vh_period_year") == "1890")
        chk("viharadhipathi_date = 2025-06-01", str(d.get("viharadhipathi_date","")).startswith("2025-06-01"))
        chk("vh_vname = Stage-F UPDATED",    "Stage-F UPDATED" in str(d.get("vh_vname","")))
        chk("vh_updated_at changed",         d.get("vh_updated_at") != d.get("vh_created_at"),
            (d.get("vh_updated_at"), d.get("vh_created_at")), "updated≠created")
    except Exception as e:
        print(f"  {ERR} {e}")

# ── 6. READ_ALL + Stage F field presence ────────────────────────────────────
print("\n" + "="*60)
print("STEP 6 · READ_ALL — pagination + Stage F fields in list items")
print("="*60)
try:
    rs = post("/vihara-data/manage", {"action":"READ_ALL","payload":{"page":1,"limit":5}})
    chk("status=success",       rs.get("status") == "success")
    recs = rs.get("data", [])
    chk("returns list",         isinstance(recs, list))
    chk("has records",          len(recs) > 0, len(recs), ">0")
    chk("totalRecords present", rs.get("totalRecords") is not None)
    chk("page=1 echoed",        rs.get("page") == 1)
    chk("limit=5 echoed",       rs.get("limit") == 5)
    if recs:
        first = recs[0]
        for k in ["vh_bypass_no_detail","vh_bypass_no_chief","vh_bypass_ltr_cert",
                  "vh_period_era","vh_period_year","vh_period_month",
                  "vh_period_day","vh_period_notes","viharadhipathi_date"]:
            chk(f"field '{k}' in list items", k in first)
except Exception as e:
    print(f"  {ERR} {e}"); import traceback; traceback.print_exc()

# ── 7. SEARCH ────────────────────────────────────────────────────────────────
print("\n" + "="*60)
print("STEP 7 · SEARCH — by TRN, by name, out-of-range page")
print("="*60)
if created_trn:
    try:
        rs = post("/vihara-data/manage", {"action":"READ_ALL","payload":{"page":1,"limit":10,"search_key":created_trn}})
        chk("search by TRN: ok",      rs.get("status") == "success")
        res = rs.get("data", [])
        chk("search by TRN: results", len(res) > 0, len(res), ">0")
        chk("search by TRN: finds record", any(r.get("vh_id")==vh_id for r in res))
    except Exception as e:
        print(f"  {ERR} {e}")

try:
    rs = post("/vihara-data/manage", {"action":"READ_ALL","payload":{"page":1,"limit":10,"search_key":f"Stage-F UPDATED"}})
    chk("search by name: ok",      rs.get("status") == "success")
    res = rs.get("data", [])
    chk("search by name: results", len(res) > 0, len(res), ">0")
    chk("search by name: correct", any(r.get("vh_id")==vh_id for r in res))
except Exception as e:
    print(f"  {ERR} {e}")

try:
    rs = post("/vihara-data/manage", {"action":"READ_ALL","payload":{"page":9999,"limit":5}})
    chk("out-of-range page: no crash",    rs.get("status") == "success")
    chk("out-of-range page: empty list",  isinstance(rs.get("data",[]), list))
except Exception as e:
    print(f"  {ERR} {e}")

# ── Summary ──────────────────────────────────────────────────────────────────
total = ok + fail
print("\n" + "="*60)
print("STAGE F · INTEGRATION TEST RESULTS")
print("="*60)
print(f"  Total   {total}")
print(f"  Passed  {ok}   {OK}")
print(f"  Failed  {fail}  {ERR if fail else OK}")
print(f"  Record  vh_id={vh_id}  trn={created_trn}")
if fail == 0:
    print("\n  ALL TESTS PASSED ✅")
    print("  Stage F CRUD + Search confirmed healthy across BE + DB")
else:
    print(f"\n  {fail} check(s) FAILED — review output above")
print("="*60)
